export default {
  "login": "juanpablosolana",
  "id": 12266308,
  "node_id": "MDQ6VXNlcjEyMjY2MzA4",
  "avatar_url": "https://avatars.githubusercontent.com/u/12266308?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/juanpablosolana",
  "html_url": "https://github.com/juanpablosolana",
  "followers_url": "https://api.github.com/users/juanpablosolana/followers",
  "following_url": "https://api.github.com/users/juanpablosolana/following{/other_user}",
  "gists_url": "https://api.github.com/users/juanpablosolana/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/juanpablosolana/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/juanpablosolana/subscriptions",
  "organizations_url": "https://api.github.com/users/juanpablosolana/orgs",
  "repos_url": "https://api.github.com/users/juanpablosolana/repos",
  "events_url": "https://api.github.com/users/juanpablosolana/events{/privacy}",
  "received_events_url": "https://api.github.com/users/juanpablosolana/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Juan Pablo Solana Ortiz",
  "company": null,
  "blog": "pablosolana.dev",
  "location": "Pachuca Hidalgo México",
  "email": null,
  "hireable": true,
  "bio": "Full Stack JS Developer ",
  "twitter_username": null,
  "public_repos": 57,
  "public_gists": 0,
  "followers": 9,
  "following": 19,
  "created_at": "2015-05-06T04:34:18Z",
  "updated_at": "2022-09-08T16:02:33Z"
}